# SVM

In [69]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import classification_report

In [70]:
data = pd.read_csv('data/bitstampUSD_1-min_data_2012-01-01_to_2021-03-31.csv')
data.head()

Timestamp  Open  High   Low  Close  Volume_(BTC)  Volume_(Currency)  \
0  1325317920  4.39  4.39  4.39   4.39      0.455581                2.0   
1  1325317980   NaN   NaN   NaN    NaN           NaN                NaN   
2  1325318040   NaN   NaN   NaN    NaN           NaN                NaN   
3  1325318100   NaN   NaN   NaN    NaN           NaN                NaN   
4  1325318160   NaN   NaN   NaN    NaN           NaN                NaN   

   Weighted_Price  
0            4.39  
1             NaN  
2             NaN  
3             NaN  
4             NaN

In [71]:
data = data.drop(['Timestamp', 'Open', 'High', 'Low', 'Volume_(BTC)','Volume_(Currency)','Weighted_Price'], axis=1)
data = data.dropna()
data.head()

Close
0      4.39
478    4.39
547    4.57
548    4.58
1224   4.58

In [72]:
days_to_predict = 30

In [73]:
data['Predictions'] = data[['Close']].shift(-days_to_predict)
data

Close  Predictions
0            4.39         6.15
478          4.39         6.19
547          4.57         6.23
548          4.58         6.25
1224         4.58         6.46
...           ...          ...
4857372  58686.00          NaN
4857373  58685.81          NaN
4857374  58723.84          NaN
4857375  58760.59          NaN
4857376  58778.18          NaN

[3613769 rows x 2 columns]

In [74]:
data.tail(31)

Close  Predictions
4857345  58748.45     58778.18
4857346  58744.88          NaN
4857347  58736.03          NaN
4857348  58755.94          NaN
4857349  58704.68          NaN
4857350  58728.74          NaN
4857351  58669.75          NaN
4857352  58628.24          NaN
4857353  58642.47          NaN
4857354  58600.20          NaN
4857355  58616.45          NaN
4857356  58616.33          NaN
4857357  58616.33          NaN
4857358  58620.59          NaN
4857359  58608.38          NaN
4857360  58600.00          NaN
4857361  58600.00          NaN
4857362  58666.54          NaN
4857363  58702.79          NaN
4857364  58677.70          NaN
4857365  58644.13          NaN
4857366  58689.44          NaN
4857367  58699.90          NaN
4857369  58698.50          NaN
4857370  58739.95          NaN
4857371  58714.31          NaN
4857372  58686.00          NaN
4857373  58685.81          NaN
4857374  58723.84          NaN
4857375  58760.59          NaN
4857376  58778.18          NaN

In [75]:
X = data.drop(['Predictions'], 1)
X = np.array(X)
X, X.shape

(array([[4.390000e+00],
        [4.390000e+00],
        [4.570000e+00],
        ...,
        [5.872384e+04],
        [5.876059e+04],
        [5.877818e+04]]),
 (3613769, 1))

In [76]:
last_instance = len(data) - days_to_predict

In [77]:
X = X[: last_instance]
X, X.shape

(array([[4.390000e+00],
        [4.390000e+00],
        [4.570000e+00],
        ...,
        [5.873096e+04],
        [5.872165e+04],
        [5.874845e+04]]),
 (3613739, 1))

In [78]:
X = X[-50000:]
X, X.shape

(array([[50722.85],
        [50695.65],
        [50669.43],
        ...,
        [58730.96],
        [58721.65],
        [58748.45]]),
 (50000, 1))

In [79]:
y = data['Predictions']
y = np.array(y)
y, y.shape

(array([6.15, 6.19, 6.23, ...,  nan,  nan,  nan]), (3613769,))

In [80]:
y = y[: last_instance]
y, y.shape

(array([6.150000e+00, 6.190000e+00, 6.230000e+00, ..., 5.872384e+04,
        5.876059e+04, 5.877818e+04]),
 (3613739,))

In [81]:
y = y[-50000:]
y, y.shape

(array([50992.97, 50886.49, 50932.86, ..., 58723.84, 58760.59, 58778.18]),
 (50000,))

In [82]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 101) # TODO stratify = y

In [83]:
from sklearn.svm import SVR
svr_rbf = SVR(kernel = 'rbf', gamma = 0.00001)

In [84]:
svr_rbf.fit(X_train, y_train)

SVR(gamma=1e-05)

In [85]:
svr_rbf_score = svr_rbf.score(X_test, y_test)
svr_rbf_score

0.36114608876431364

In [68]:
svr_rbf_predictions = svr_rbf.predict(X_test)